---
# tasks file for roles/launch-frontend
- name: Launch frontend container
  docker_container:
    name: frontend-devops
    image: edwhlt/tp_devops-frontend:latest
    ports:
      - "81:80"
    networks:
      - name: netapp
    state: started
    recreate: yes
    pull: true
  become: yes
