# tasks file for roles/launch-database
---
- name: Launch database container
  docker_container:
    name: db-devops
    image: edwhlt/tp_devops-database:latest
    volumes:
      - /database/data:/var/lib/postgresql/data
      - /database/backup:/var/lib/postgresql/backup
    networks:
      - name: netapp
    state: started
    recreate: yes
    pull: true
  become: yes
