name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["Docker"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your-server-ip >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
        continue-on-error: true

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False  # Pour éviter la vérification de la clé SSH
