name: CI devops 2023

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # Assurez-vous que la version de setup-java est correcte
        with:
          java-version: 17 # Spécifiez la version de Java que vous souhaitez

      - name: Build and test with Maven
        run: mvn clean verify -DskipTests --file backend/pom.xml
