name: CI devops 2023

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # Assurez-vous que la version de setup-java est correcte
        with:
          java-version: 17 # Spécifiez la version de Java que vous souhaitez
          distribution: 'adopt'

      - name: Build and test with Maven
        run: mvn clean verify -DskipTests --file backend/pom.xml


  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
  
   # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
        
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp_devops:backend
          push: ${{ github.ref == 'refs/heads/master' }}
    
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database # Mettez ici le chemin relatif vers le répertoire de votre base de données
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp_devops:database
          push: ${{ github.ref == 'refs/heads/master' }}
    
    
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./frontend # Mettez ici le chemin relatif vers le répertoire de votre serveur HTTP
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp_devops:frontend
          push: ${{ github.ref == 'refs/heads/master' }}


  sonarcloud:
    runs-on: ubuntu-22.04
    steps:
      - name: SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=TP_devops -Dsonar.organization=edwhlt -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./backend/pom.xml

